import { rm } from "node:fs/promises";
import * as path from "node:path";
import { generateFiles, type OutputEntry } from "fumadocs-openapi";
import { createOpenAPI } from "fumadocs-openapi/server";

/**
 * Generate the interactive API reference pages from the OpenAPI specs.
 *
 * Each spec is generated into its own folder so tag groups never collide across
 * schemas (both surfaces have, e.g., a "Health" tag). One page per operation,
 * grouped into folders by tag. The generated `<APIPage />` bodies are rendered
 * at request time by the shared server in `src/lib/openapi.ts` — keep the input
 * paths identical between the two files.
 *
 * A folder is only routable when it has an `index.mdx`; without one the surface
 * roots (`.../gateway`, `.../core`) 404 even though the parent api-reference
 * page links straight to them. `fumadocs-openapi`'s built-in `index` option
 * skips group (tag-folder) entries, which is everything when `groupBy: "tag"`,
 * so we build the landing pages ourselves in `beforeWrite` instead.
 */
const CONTENT_ROOT = path.join("content", "docs");
const API_DIR = path.join(CONTENT_ROOT, "develop", "api-reference");

const specs = [
  {
    input: "./specs/gateway-openapi.yaml",
    out: "gateway",
    title: "Gateway API",
    description:
      "The OpenAI-compatible control layer: chat, image, and audio generation plus routing, evals, audit, and governance.",
  },
  {
    input: "./specs/core-openapi.json",
    out: "core",
    title: "Core API",
    description:
      "The local orchestration backend: chat, agents, conversations, models, skills, MCP tools, spaces/RAG, sidecars, and more.",
  },
] as const;

const MAX_CARD_DESCRIPTION = 160;

function cleanDescription(raw: string | undefined): string | undefined {
  if (!raw) {
    return undefined;
  }
  const collapsed = raw.replace(/\s+/g, " ").trim();
  if (collapsed.length === 0) {
    return undefined;
  }
  return collapsed.length > MAX_CARD_DESCRIPTION
    ? `${collapsed.slice(0, MAX_CARD_DESCRIPTION - 1).trimEnd()}…`
    : collapsed;
}

/**
 * Build the surface landing page: one `## <Tag>` section per tag group, each
 * with a `<Cards>` grid linking to that group's operation pages. `entry.path`
 * is relative to the surface output folder (e.g. `inference/createChat.mdx`),
 * so the route is the surface base + that path without the `.mdx` extension.
 */
function landingPage(
  spec: (typeof specs)[number],
  entries: OutputEntry[],
): string {
  const surfaceBase = `/docs/develop/api-reference/${spec.out}`;
  const href = (entryPath: string) =>
    `${surfaceBase}/${entryPath
      .split(path.sep)
      .join("/")
      .replace(/\.mdx$/, "")}`;

  const card = (entry: OutputEntry): string => {
    const description = cleanDescription(entry.info.description);
    const descriptionAttr = description
      ? ` description={${JSON.stringify(description)}}`
      : "";
    return `  <Card href=${JSON.stringify(href(entry.path))} title=${JSON.stringify(entry.info.title)}${descriptionAttr} />`;
  };

  const lines: string[] = [];
  for (const group of entries) {
    if (group.type === "group") {
      const operations = group.entries.filter(
        (child) => child.type !== "group",
      );
      if (operations.length === 0) {
        continue;
      }
      lines.push("", `## ${group.info.title}`);
      const groupDescription = cleanDescription(group.info.description);
      if (groupDescription) {
        lines.push("", groupDescription);
      }
      lines.push("", "<Cards>", ...operations.map(card), "</Cards>");
    } else {
      lines.push("", "<Cards>", card(group), "</Cards>");
    }
  }

  const frontmatter = [
    "---",
    `title: ${JSON.stringify(spec.title)}`,
    `description: ${JSON.stringify(spec.description)}`,
    "---",
  ].join("\n");
  const banner =
    "{/* Landing page generated by scripts/generate-docs.ts — edit the script, not this file. */}";

  return `${frontmatter}\n\n${banner}\n${lines.join("\n")}\n`;
}

async function main() {
  for (const spec of specs) {
    const output = path.join(API_DIR, spec.out);
    // Drop previously generated pages so removed endpoints don't linger.
    await rm(output, { recursive: true, force: true });

    const server = createOpenAPI({ input: [spec.input] });
    await generateFiles({
      input: server,
      output,
      per: "operation",
      groupBy: "tag",
      includeDescription: true,
      meta: true,
      beforeWrite(files) {
        const entries = Object.values(this.generatedEntries).flat();
        // `path` is relative to `output`, so this writes `<output>/index.mdx`.
        files.push({ path: "index.mdx", content: landingPage(spec, entries) });
      },
    });
  }
}

main().catch((error) => {
  process.exitCode = 1;
  throw error;
});
