// This file is generated by apps/fumadocs/scripts/generate-ui-docs.ts.
// Keep the import paths aligned with the @ryu/ui package export map.

type UiComponentModule = Record<string, unknown>;

export const UI_COMPONENT_MODULE_LOADERS: Record<
  string,
  () => Promise<UiComponentModule>
> = {
  "components/alert": async () =>
    (await import("@ryu/ui/components/alert")) as UiComponentModule,
  "components/aspect-ratio": async () =>
    (await import("@ryu/ui/components/aspect-ratio")) as UiComponentModule,
  "components/award-badge": async () =>
    (await import("@ryu/ui/components/award-badge")) as UiComponentModule,
  "components/badge": async () =>
    (await import("@ryu/ui/components/badge")) as UiComponentModule,
  "components/bouncy-accordion": async () =>
    (await import("@ryu/ui/components/bouncy-accordion")) as UiComponentModule,
  "components/button": async () =>
    (await import("@ryu/ui/components/button")) as UiComponentModule,
  "components/checkbox": async () =>
    (await import("@ryu/ui/components/checkbox")) as UiComponentModule,
  "components/connection-status": async () =>
    (await import("@ryu/ui/components/connection-status")) as UiComponentModule,
  "components/elastic-slider": async () =>
    (await import("@ryu/ui/components/elastic-slider")) as UiComponentModule,
  "components/input": async () =>
    (await import("@ryu/ui/components/input")) as UiComponentModule,
  "components/kbd": async () =>
    (await import("@ryu/ui/components/kbd")) as UiComponentModule,
  "components/label": async () =>
    (await import("@ryu/ui/components/label")) as UiComponentModule,
  "components/marketplace-access-badge": async () =>
    (await import(
      "@ryu/ui/components/marketplace-access-badge"
    )) as UiComponentModule,
  "components/native-select": async () =>
    (await import("@ryu/ui/components/native-select")) as UiComponentModule,
  "components/profile-charts": async () =>
    (await import("@ryu/ui/components/profile-charts")) as UiComponentModule,
  "components/progress": async () =>
    (await import("@ryu/ui/components/progress")) as UiComponentModule,
  "components/radio-group": async () =>
    (await import("@ryu/ui/components/radio-group")) as UiComponentModule,
  "components/run-status-timeline": async () =>
    (await import(
      "@ryu/ui/components/run-status-timeline"
    )) as UiComponentModule,
  "components/scroll-area": async () =>
    (await import("@ryu/ui/components/scroll-area")) as UiComponentModule,
  "components/select": async () =>
    (await import("@ryu/ui/components/select")) as UiComponentModule,
  "components/separator": async () =>
    (await import("@ryu/ui/components/separator")) as UiComponentModule,
  "components/sileo": async () =>
    (await import("@ryu/ui/components/sileo")) as UiComponentModule,
  "components/skeleton": async () =>
    (await import("@ryu/ui/components/skeleton")) as UiComponentModule,
  "components/slider": async () =>
    (await import("@ryu/ui/components/slider")) as UiComponentModule,
  "components/spinner": async () =>
    (await import("@ryu/ui/components/spinner")) as UiComponentModule,
  "components/status-badge": async () =>
    (await import("@ryu/ui/components/status-badge")) as UiComponentModule,
  "components/success-check": async () =>
    (await import("@ryu/ui/components/success-check")) as UiComponentModule,
  "components/switch": async () =>
    (await import("@ryu/ui/components/switch")) as UiComponentModule,
  "components/textarea": async () =>
    (await import("@ryu/ui/components/textarea")) as UiComponentModule,
  "components/visually-hidden-input": async () =>
    (await import(
      "@ryu/ui/components/visually-hidden-input"
    )) as UiComponentModule,
  "components/accordion": async () =>
    (await import("@ryu/ui/components/accordion")) as UiComponentModule,
  "components/breadcrumb": async () =>
    (await import("@ryu/ui/components/breadcrumb")) as UiComponentModule,
  "components/card": async () =>
    (await import("@ryu/ui/components/card")) as UiComponentModule,
  "components/collapsible": async () =>
    (await import("@ryu/ui/components/collapsible")) as UiComponentModule,
  "components/empty": async () =>
    (await import("@ryu/ui/components/empty")) as UiComponentModule,
  "components/item": async () =>
    (await import("@ryu/ui/components/item")) as UiComponentModule,
  "components/motion-navigation-menu": async () =>
    (await import(
      "@ryu/ui/components/motion-navigation-menu"
    )) as UiComponentModule,
  "components/navigation-menu": async () =>
    (await import("@ryu/ui/components/navigation-menu")) as UiComponentModule,
  "components/page-header": async () =>
    (await import("@ryu/ui/components/page-header")) as UiComponentModule,
  "components/pagination": async () =>
    (await import("@ryu/ui/components/pagination")) as UiComponentModule,
  "components/resizable": async () =>
    (await import("@ryu/ui/components/resizable")) as UiComponentModule,
  "components/sidebar": async () =>
    (await import("@ryu/ui/components/sidebar")) as UiComponentModule,
  "components/tabs": async () =>
    (await import("@ryu/ui/components/tabs")) as UiComponentModule,
  "components/tabs-subtle": async () =>
    (await import("@ryu/ui/components/tabs-subtle")) as UiComponentModule,
  "components/alert-dialog": async () =>
    (await import("@ryu/ui/components/alert-dialog")) as UiComponentModule,
  "components/command": async () =>
    (await import("@ryu/ui/components/command")) as UiComponentModule,
  "components/context-menu": async () =>
    (await import("@ryu/ui/components/context-menu")) as UiComponentModule,
  "components/dialog": async () =>
    (await import("@ryu/ui/components/dialog")) as UiComponentModule,
  "components/drawer": async () =>
    (await import("@ryu/ui/components/drawer")) as UiComponentModule,
  "components/dropdown-menu": async () =>
    (await import("@ryu/ui/components/dropdown-menu")) as UiComponentModule,
  "components/hover-card": async () =>
    (await import("@ryu/ui/components/hover-card")) as UiComponentModule,
  "components/menubar": async () =>
    (await import("@ryu/ui/components/menubar")) as UiComponentModule,
  "components/overflow-actions": async () =>
    (await import("@ryu/ui/components/overflow-actions")) as UiComponentModule,
  "components/popover": async () =>
    (await import("@ryu/ui/components/popover")) as UiComponentModule,
  "components/sheet": async () =>
    (await import("@ryu/ui/components/sheet")) as UiComponentModule,
  "components/tooltip": async () =>
    (await import("@ryu/ui/components/tooltip")) as UiComponentModule,
  "components/button-group": async () =>
    (await import("@ryu/ui/components/button-group")) as UiComponentModule,
  "components/calendar": async () =>
    (await import("@ryu/ui/components/calendar")) as UiComponentModule,
  "components/color-picker": async () =>
    (await import("@ryu/ui/components/color-picker")) as UiComponentModule,
  "components/combobox": async () =>
    (await import("@ryu/ui/components/combobox")) as UiComponentModule,
  "components/field": async () =>
    (await import("@ryu/ui/components/field")) as UiComponentModule,
  "components/input-group": async () =>
    (await import("@ryu/ui/components/input-group")) as UiComponentModule,
  "components/motion/otp-input": async () =>
    (await import("@ryu/ui/components/motion/otp-input")) as UiComponentModule,
  "components/table": async () =>
    (await import("@ryu/ui/components/table")) as UiComponentModule,
  "components/toggle": async () =>
    (await import("@ryu/ui/components/toggle")) as UiComponentModule,
  "components/toggle-group": async () =>
    (await import("@ryu/ui/components/toggle-group")) as UiComponentModule,
  "components/attachment": async () =>
    (await import("@ryu/ui/components/attachment")) as UiComponentModule,
  "components/avatar": async () =>
    (await import("@ryu/ui/components/avatar")) as UiComponentModule,
  "components/bubble": async () =>
    (await import("@ryu/ui/components/bubble")) as UiComponentModule,
  "components/emoji-picker": async () =>
    (await import("@ryu/ui/components/emoji-picker")) as UiComponentModule,
  "components/message": async () =>
    (await import("@ryu/ui/components/message")) as UiComponentModule,
  "components/message-scroller": async () =>
    (await import("@ryu/ui/components/message-scroller")) as UiComponentModule,
  "components/chart": async () =>
    (await import("@ryu/ui/components/chart")) as UiComponentModule,
  "components/contributions-graph": async () =>
    (await import(
      "@ryu/ui/components/contributions-graph"
    )) as UiComponentModule,
  "components/motion/action-swap-roll": async () =>
    (await import(
      "@ryu/ui/components/motion/action-swap-roll"
    )) as UiComponentModule,
  "components/apple-hello-effect": async () =>
    (await import(
      "@ryu/ui/components/apple-hello-effect"
    )) as UiComponentModule,
  "components/motion/button/index": async () =>
    (await import(
      "@ryu/ui/components/motion/button/index"
    )) as UiComponentModule,
  "components/motion/checkbox": async () =>
    (await import("@ryu/ui/components/motion/checkbox")) as UiComponentModule,
  "components/motion/chromatic-text-reveal": async () =>
    (await import(
      "@ryu/ui/components/motion/chromatic-text-reveal"
    )) as UiComponentModule,
  "components/icon-swap": async () =>
    (await import("@ryu/ui/components/icon-swap")) as UiComponentModule,
  "components/motion/input": async () =>
    (await import("@ryu/ui/components/motion/input")) as UiComponentModule,
  "components/motion/loader": async () =>
    (await import("@ryu/ui/components/motion/loader")) as UiComponentModule,
  "components/morph-icon": async () =>
    (await import("@ryu/ui/components/morph-icon")) as UiComponentModule,
  "components/motion-highlight": async () =>
    (await import("@ryu/ui/components/motion-highlight")) as UiComponentModule,
  "components/number-pop-in": async () =>
    (await import("@ryu/ui/components/number-pop-in")) as UiComponentModule,
  "components/number-ticker": async () =>
    (await import("@ryu/ui/components/number-ticker")) as UiComponentModule,
  "components/motion/preview-rail": async () =>
    (await import(
      "@ryu/ui/components/motion/preview-rail"
    )) as UiComponentModule,
  "components/progressive-blur": async () =>
    (await import("@ryu/ui/components/progressive-blur")) as UiComponentModule,
  "components/motion/radio": async () =>
    (await import("@ryu/ui/components/motion/radio")) as UiComponentModule,
  "components/motion/range-slider": async () =>
    (await import(
      "@ryu/ui/components/motion/range-slider"
    )) as UiComponentModule,
  "components/motion/range-slider-fluid": async () =>
    (await import(
      "@ryu/ui/components/motion/range-slider-fluid"
    )) as UiComponentModule,
  "components/motion/range-slider-wave": async () =>
    (await import(
      "@ryu/ui/components/motion/range-slider-wave"
    )) as UiComponentModule,
  "components/rolling-number": async () =>
    (await import("@ryu/ui/components/rolling-number")) as UiComponentModule,
  "components/stagger-reveal": async () =>
    (await import("@ryu/ui/components/stagger-reveal")) as UiComponentModule,
  "components/motion/text-scramble": async () =>
    (await import(
      "@ryu/ui/components/motion/text-scramble"
    )) as UiComponentModule,
  "components/motion/text-shimmer": async () =>
    (await import(
      "@ryu/ui/components/motion/text-shimmer"
    )) as UiComponentModule,
  "components/text-swap": async () =>
    (await import("@ryu/ui/components/text-swap")) as UiComponentModule,
  "components/voice-activity-beam": async () =>
    (await import(
      "@ryu/ui/components/voice-activity-beam"
    )) as UiComponentModule,
  "components/wave": async () =>
    (await import("@ryu/ui/components/wave")) as UiComponentModule,
  "components/dither-kit/avatar": async () =>
    (await import("@ryu/ui/components/dither-kit/avatar")) as UiComponentModule,
  "components/button-download": async () =>
    (await import("@ryu/ui/components/button-download")) as UiComponentModule,
  "components/carousel": async () =>
    (await import("@ryu/ui/components/carousel")) as UiComponentModule,
  "components/employee-badge": async () =>
    (await import("@ryu/ui/components/employee-badge")) as UiComponentModule,
  "components/dither-kit/gradient": async () =>
    (await import(
      "@ryu/ui/components/dither-kit/gradient"
    )) as UiComponentModule,
  "components/lanyard/Lanyard": async () =>
    (await import("@ryu/ui/components/lanyard/Lanyard")) as UiComponentModule,
  "components/logo": async () =>
    (await import("@ryu/ui/components/logo")) as UiComponentModule,
  "components/marker": async () =>
    (await import("@ryu/ui/components/marker")) as UiComponentModule,
  "components/plan-badge": async () =>
    (await import("@ryu/ui/components/plan-badge")) as UiComponentModule,
  "components/signature": async () =>
    (await import("@ryu/ui/components/signature")) as UiComponentModule,
  "components/agents/agent-activity": async () =>
    (await import(
      "@ryu/ui/components/agents/agent-activity"
    )) as UiComponentModule,
  "components/agents/agent-code": async () =>
    (await import("@ryu/ui/components/agents/agent-code")) as UiComponentModule,
  "components/agents/agent-disclosure": async () =>
    (await import(
      "@ryu/ui/components/agents/agent-disclosure"
    )) as UiComponentModule,
  "components/agents/approval-card": async () =>
    (await import(
      "@ryu/ui/components/agents/approval-card"
    )) as UiComponentModule,
  "components/agents/citations": async () =>
    (await import("@ryu/ui/components/agents/citations")) as UiComponentModule,
  "components/agents/code-block": async () =>
    (await import("@ryu/ui/components/agents/code-block")) as UiComponentModule,
  "components/agents/file-diff": async () =>
    (await import("@ryu/ui/components/agents/file-diff")) as UiComponentModule,
  "components/agents/loading-states": async () =>
    (await import(
      "@ryu/ui/components/agents/loading-states"
    )) as UiComponentModule,
  "components/agents/message-scroller": async () =>
    (await import(
      "@ryu/ui/components/agents/message-scroller"
    )) as UiComponentModule,
  "components/agents/loading-states/thinking-shimmer": async () =>
    (await import(
      "@ryu/ui/components/agents/loading-states/thinking-shimmer"
    )) as UiComponentModule,
  "components/agents/todo-list": async () =>
    (await import("@ryu/ui/components/agents/todo-list")) as UiComponentModule,
  "components/agents/tool-approval": async () =>
    (await import(
      "@ryu/ui/components/agents/tool-approval"
    )) as UiComponentModule,
  "components/agents/tool-result": async () =>
    (await import(
      "@ryu/ui/components/agents/tool-result"
    )) as UiComponentModule,
};

